const words = [
  "Accept",
  "Ansvar",
  "At kunne sige fra",
  "At kunne være sig selv",
  "At kunne ytre",
  "Befrielse",
  "Begrænsninger",
  "Det er du alligevel",
  "Detektor",
  "Egen omsorg",
  "Familie",
  "Fred",
  "Fremtid",
  "Forandring",
  "Forandring (orden)",
  "Frihed",
  "Frihed fra – frihed til",
  "Følelser",
  "Gå hele vejen",
  "Grænser",
  "Hab",
  "Helhjertethed",
  "Hjælp mig",
  "Idéer",
  "Indsats",
  "Kernefred",
  "Konsekvens",
  "Kærlighed",
  "Lyst",
  "Meditation",
  "Mod",
  "Motion",
  "Orden i eget hus",
  "Orden og ro",
  "Orden og stil",
  "Respekt",
  "Ritualer",
  "Ro",
  "Selvomsorg",
  "Selvrespekt",
  "Skam",
  "Skabe orden",
  "Stabilitet",
  "Styrke",
  "Styrke og mod",
  "Stærk værdier",
  "Søvn",
  "Taknemmelighed",
  "Tilgivelse",
  "Tillid",
  "Tryghed",
  "Udvikling",
  "Uafhængighed",
  "Valg",
  "Venlighed",
  "Venskab",
  "Viljestyrke",
  "Visdom",
  "Vækst",
  "Vrede",
  "Ydmyghed"
];


const today = new Date();
const dayNumber = Math.floor(today / (1000 * 60 * 60 * 24));
const word = words[dayNumber % words.length];

document.getElementById("word").textContent = word;
document.getElementById("date").textContent =
  today.toDateString();
